on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

name: bench

permissions:
  deployments: write
  contents: write

jobs:
  bench:
    name: bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run benchmarks
        run: cargo bench | tee output.txt
      - name: Upload criterion report
        uses: actions/upload-artifact@v3
        with:
          name: criterion
          path: target/criterion
      - name: Publish benchmarks to gh-pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: backtrack-rs criterion
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
